# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('review_date', models.DateTimeField()),
                ('premises', models.CharField(max_length=100)),
                ('service', models.CharField(choices=[('Горячая вода', 'Горячая вода'), ('Холодная вода', 'Холодная вода'), ('Электричество', 'Электричество')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Testimony',
            fields=[
                ('testimony_id', models.AutoField(primary_key=True, serialize=False)),
                ('value', models.PositiveIntegerField(default=0)),
                ('divice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='python_app.Device')),
            ],
        ),
    ]
