# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-14 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('python_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimony',
            old_name='divice_id',
            new_name='device_id',
        ),
        migrations.AlterField(
            model_name='testimony',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
