# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-15 02:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('python_app', '0002_auto_20161115_0124'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='user_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
